name: controlling_mix
description: Example of how to control the level of mix in animations
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive:
    # Until the new version of `rive` for Flutter is published, we depend on the Git commit.
    # See https://github.com/rive-app/rive-flutter/commit/66305cb511f4787c3b6cecb09c15b18bd9c5149d.
    git:
      url: https://github.com/rive-app/rive-flutter
      ref: 66305cb511f4787c3b6cecb09c15b18bd9c5149d

flutter:
  uses-material-design: true

  assets:
    - assets/
